# version: "3"

x-logging: &default-logging
   options:
      max-size: "10m"
      max-file: "5"
   driver: json-file

# https://hub.docker.com/r/tailscale/tailscale
# https://tailscale.com/kb/1282/docker
services:
   tailscale:
      image: tailscale/tailscale:latest
      container_name: tailscale
      hostname: nightscout-ts
      ports:
         - 1337:1337
      environment:
         - TS_AUTHKEY=${MY_TS_KEY}
         - TS_STATE_DIR=/var/lib/tailscale
         - TS_USERSPACE=true
         - TS_SERVE_CONFIG=/config/serve.json
      # devices:
      #    - /dev/net/tun:/dev/net/tun
      volumes:
         - ./tailscale-state:/var/lib/tailscale
         - ./tailscale-config:/config
      cap_add:
         - net_admin
         - net_raw
      restart: unless-stopped
      env_file: .env
      #network_mode: "service:nightscout"

   mongo:
      image: mongo:4.4 # old cpu :(
      restart: always
      volumes:
         - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached
      logging: *default-logging

   nightscout:
      image: nightscout/cgm-remote-monitor:15.0.7 # old cpu :(
      container_name: nightscout
      restart: always
      #ports:
      #- "1337:1337"
      depends_on:
         - mongo
         - tailscale
      logging: *default-logging
      network_mode: "service:tailscale"
      environment:
         ### Variables for the container
         NODE_ENV: production
         INSECURE_USE_HTTP: "true"
         # Listen on all container interfaces so reverse proxies and other containers can reach Nightscout
         #NIGHTSCOUT_HOSTNAME: "0.0.0.0"
         MONGO_CONNECTION: mongodb://mongo:27017/nightscout
         API_SECRET: ${MY_API_SECRET}
         # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
         # When readable, anyone can view Nightscout without a token. Setting it to denied will require
         # a token from every visit, using status-only will enable api-secret based login.
         AUTH_DEFAULT_ROLES: readable
         # For all other settings, please refer to the Environment section of the README
         # https://github.com/nightscout/cgm-remote-monitor#environment
         DISPLAY_UNITS: mmol
         TIME_FORMAT: 24
         TZ: Europe/Prague
         # Plugins:
         ENABLE: devicestatus dbsize iob cob cage sage basal pump openaps
         # Maybe: careportal boluscalc bwp
         # Alarms
         ALARM_URGENT_HIGH: off
         ALARM_HIGH: off
         ALARM_LOW: off
         ALARM_URGENT_LOW: off
         ## Missing data alarm
         ALARM_TIMEAGO_WARN: off
         ALARM_TIMEAGO_URGENT: off
         TIMEAGO_ENABLE_ALERTS: false
         SHOW_FORECAST: openaps
         CUSTOM_TITLE: puppy sugar
         THEME: colors
         SCALE_Y: linear
         BASAL_RENDER: default
