version: "3"

x-logging: &default-logging
   options:
      max-size: "10m"
      max-file: "5"
   driver: json-file

services:
   tailscale:
      image: tailscale/tailscale:latest
      container_name: tailscale
      hostname: nightscout-ts
      environment:
      - TS_AUTHKEY=${MY_TS_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      # - TS_USERSPACE=false
      volumes:
      - ./tailscale-state:/var/lib/tailscale
      cap_add:
      - net_admin
      - net_raw
      restart: unless-stopped



   mongo:
      image: mongo:4.4 # old cpu :(
      restart: always
      volumes:
         - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached
      logging: *default-logging
      # network_mode: "service:tailscale" 

   nightscout:
      image: nightscout/cgm-remote-monitor:15.0.7 # old cpu :(
      container_name: nightscout
      restart: always
      #ports:
      #- "1337:1337"
      depends_on:
         - mongo
         - tailscale
      logging: *default-logging
      network_mode: "service:tailscale"
      environment:
         ### Variables for the container
         NODE_ENV: production
         TZ: ${MY_TZ}
         INSECURE_USE_HTTP: "true"
         # Listen on all container interfaces so reverse proxies and other containers can reach Nightscout
         #NIGHTSCOUT_HOSTNAME: "0.0.0.0"
         MONGO_CONNECTION: mongodb://mongo:27017/nightscout
         API_SECRET: ${MY_API_SECRET}
         # See https://github.com/nightscout/cgm-remote-monitor#plugins for details
         ENABLE: careportal rawbg iob cob delta direction upbat timeago devicestatus errorcodes ar2 profile cage sage basal bolus pump openaps dbsize
         SHOW_FORECAST: openaps
         # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
         # When readable, anyone can view Nightscout without a token. Setting it to denied will require
         # a token from every visit, using status-only will enable api-secret based login.
         AUTH_DEFAULT_ROLES: readable
         # For all other settings, please refer to the Environment section of the README
         # https://github.com/nightscout/cgm-remote-monitor#environment
         DISPLAY_UNITS: mmol/L